# Artificial Neural Network

### Importing the libraries

In [63]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [64]:
tf.__version__

'2.4.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [65]:
dataset = pd.read_csv('Churn_Modelling.csv') # load csv file

# column 0-2 is irrelavent to the classification, so start from 3 to -1 (just before last column)
X = dataset.iloc[:, 3:-1].values 

# it is the result, the last column
y = dataset.iloc[:, -1].values 

In [66]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [67]:
print(y)

[1 0 1 ... 1 1 0]


### Additional Testing

In [68]:
print(X[2]) # example get the row of 3

[502 'France' 'Female' 42 8 159660.8 3 1 0 113931.57]


In [69]:
print(X[:,0]) # example to get first column

[619 608 502 ... 709 772 792]


In [70]:
print(X[:,-1]) # last column

[101348.88 112542.58 113931.57 ... 42085.58 92888.52 38190.78]


### Encoding categorical data

Label Encoding the "Gender" column

need to use LabelEncoder and then fit_transform

fit_transform(partData)是先對partData作fit()的功能，找到該partData的整體統計特性之指標，如平均值、標準差、最大最小值等等(能依據不同目的套用這些指標在不同的轉換(即後面的transform()動作)上，再實行transform(partData)以對partData進行標準化(英文稱為normalization, 主要有兩種方法: min-max normalization or standard deviation normalization)或歸一化等動作.

In [71]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [72]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

### Additional Comment
Label Encoder => no additional column is added
OneHotEncoder => additional columns have been added and use only 0.0 and 1.0 to represent the value,
such as 1.0 0.0 0.0 to represent France, 0.0 0.0 1.0 to represent Spain

pandas is also able to do the OneHotEncoding

data_dum = pd.get_dummies(data)
pd.DataFrame(data_dum)

In [73]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [74]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [75]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

fit(): Method calculates the parameters μ and σ and saves them as internal objects.

preprocessing这个模块还提供了一个实用类StandarScaler，它可以在训练数据集上做了标准转换操作之后，把相同的转换应用到测试训练集中。

这是相当好的一个功能。可以对训练数据，测试数据应用相同的转换，以后有新的数据进来也可以直接调用，不用再重新把数据放在一起再计算一次了。

In [76]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [77]:
print(X_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


## Part 2 - Building the ANN

### Initializing the ANN

a sequence of layers and just like a computational graph

In [78]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

add a fully connectioned layer

In [79]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [80]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [81]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

https://medium.com/%E9%9B%9E%E9%9B%9E%E8%88%87%E5%85%94%E5%85%94%E7%9A%84%E5%B7%A5%E7%A8%8B%E4%B8%96%E7%95%8C/%E6%A9%9F%E5%99%A8%E5%AD%B8%E7%BF%92ml-note-sgd-momentum-adagrad-adam-optimizer-f20568c968db

對於Optimizer來說，learning rate(學習率) η 相當的重要，太小會花費太多時間學習，太大有可能會造成overfitting，無法正確學習，前面幾種Optimizer的學習率 η，都為固定值，而AdaGrad就是會依照梯度去調整 learning rate η 的優化器，Ada對我來說就是Adaptive的意思

Adam Optimizer 其實可以說就是把前面介紹的Momentum 跟 AdaGrad這二種Optimizer做結合，

Adam 保留了 Momentum 對過去梯度的方向做梯度速度調整與Adam對過去梯度的平方值做learning rate的調整，再加上Adam有做參數的”偏離校正”，使得每一次的學習率都會有個確定的範圍，會讓參數的更新較為平穩。

binary_crossentropy交叉熵损失函数，一般用于二分类：

In [82]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [83]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 826us/step - loss: 0.5360 - accuracy: 0.7833
Epoch 2/100
250/250 [==============================] - 0s 774us/step - loss: 0.4675 - accuracy: 0.7983
Epoch 3/100
250/250 [==============================] - 0s 883us/step - loss: 0.4509 - accuracy: 0.7943
Epoch 4/100
250/250 [==============================] - 0s 798us/step - loss: 0.4366 - accuracy: 0.7992
Epoch 5/100
250/250 [==============================] - 0s 855us/step - loss: 0.4330 - accuracy: 0.8094
Epoch 6/100
250/250 [==============================] - 0s 915us/step - loss: 0.4280 - accuracy: 0.8120
Epoch 7/100
250/250 [==============================] - 0s 766us/step - loss: 0.4161 - accuracy: 0.8246
Epoch 8/100
250/250 [==============================] - 0s 770us/step - loss: 0.4070 - accuracy: 0.8303
Epoch 9/100
250/250 [==============================] - 0s 762us/step - loss: 0.4000 - accuracy: 0.8317
Epoch 10/100
250/250 [==============================] - 0s 762us/step - l

Epoch 80/100
250/250 [==============================] - 0s 782us/step - loss: 0.3342 - accuracy: 0.8631
Epoch 81/100
250/250 [==============================] - 0s 778us/step - loss: 0.3379 - accuracy: 0.8674
Epoch 82/100
250/250 [==============================] - 0s 770us/step - loss: 0.3259 - accuracy: 0.8677
Epoch 83/100
250/250 [==============================] - 0s 778us/step - loss: 0.3343 - accuracy: 0.8631
Epoch 84/100
250/250 [==============================] - 0s 798us/step - loss: 0.3397 - accuracy: 0.8603
Epoch 85/100
250/250 [==============================] - 0s 798us/step - loss: 0.3225 - accuracy: 0.8758
Epoch 86/100
250/250 [==============================] - 0s 774us/step - loss: 0.3307 - accuracy: 0.8721
Epoch 87/100
250/250 [==============================] - 0s 774us/step - loss: 0.3338 - accuracy: 0.8646
Epoch 88/100
250/250 [==============================] - 0s 806us/step - loss: 0.3398 - accuracy: 0.8589
Epoch 89/100
250/250 [==============================] - 0s 959us

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

In [84]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

### additional testing

reshape =>>> numpy function

import numpy as np

arrayA = np.arange(8)
=>>> arrayA = array([0, 1, 2, 3, 4, 5, 6, 7])

np.reshape(arrayA, (2, 4))
=>>> array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
       
to show the result side by side

### additional testing

In [85]:
np.concatenate((y_test.reshape(len(y_test),1), y_test.reshape(len(y_test),1)),1)

array([[0, 0],
       [1, 1],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [86]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [87]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred) # correct vs prediction
print(cm)
accuracy_score(y_test, y_pred)

[[1535   60]
 [ 213  192]]


0.8635